### ISSUE TITLE
OEIS offers a gzip'ed version of their sequence database

### ISSUE THREAD

**Issue by drforr** [ajs/perl6-Math-Sequences#10]
https://oeis.org/stripped.gz for just the sequence A-number and values, https://oeis.org/names.gz for sequence name and A-number. Import that and you're a good chunk of the way there.

**Comment by ajs** [comment]
I appreciate the idea, but honestly, we don't want a few canned values for each sequence (though it's a fine thing to get people looking at the project). What we need is the generators that make *the whole sequences*.

**Comment by drforr** [comment]
Cool, I'm a fan of the idea as it is, and I've thought about doing it myself a few times. In the writeup I read they said that you were adding in sequences from the OEIS website and *then* filling in methods for those that can be generated easily (there's plenty of stuff in there like the Busy Beaver where adding another value to the sequence would probably win you some sort of prize, but you know that.) I just was noticing that the links to the raw database were a bit buried, and thought that you'd maybe missed it. Good luck with the project, I might even be inspired to add a few once I get done with this upcoming conference :)

**Comment by ajs** [comment]
There are three parts:

1. We already have testing that uses the sequence examples from OEIS to validate our sequences. That's done, but of course those are just short sequences from (in most OEIS cases) infinitely long runs.
2. We also have some sequences where the implementation is considered either harder than anyone is going to get to soon or not actually computationally practical, in which case getting people to help out enhancing those with some of the canned data would be great.
3. What we really need is finished sequence generators (like the handful of merges I've done for another contributor today) which requires deeply understanding what's going on in a sequence and implementing its generator in Perl. Side benefit: because we use the OEIS canned data for testing, your generator gets a test automatically!

**Comment by ajs** [comment]
Sorry to be waffly on this @drforr but I'm re-thinking my answer.

I think that what you propose has value, but not in the Integer module. Rather, I think it would be good for it to have its own module within this library; something like `Math::Sequences::OeisSamples` or the like (terrible name, but you get the idea). I've just written an OEIS function in Integer.pm and which would be the ideal entry-point to that data. I would imagine that sequences defined in Integer.pm would be returned from the OEIS function first, but then it could fall back to the samples when a NOSEQ failure occurs.

Sorry again for giving a knee-jerk response. I just hadn't understood you were talking about the WHOLE OEIS not just the "core" sequences!

**Comment by drforr** [comment]
That's correct, I was thinking more along the lines of corpus testing. Once I get back from the conference I might have some spare cycles to dedicate to this...

**Comment by drforr** [comment]
Another issue for corpus testing might be making sure the sequence extrapolates correctly. One test I'd show you is this (the Cake sequence - the max number of pieces of cake you can get cutting it with a straight knife):

is_deeply [@OEIS_Cake[1..4]], [ 1, 2, 4, 8 ]; # The first 4 terms of the sequence ("all we have to test") are ok

but

is_deeply [OEIS_Cake[1..5]], [1, 2, 4, 8, 16]; # Is wrong, the next term is 15.

So cutting a piece of cake 5 times *looks* like it should extrapolate to 16, it doesn't. That last piece is almost there but not quite.

OEIS should give you enough terms to make sure you don't extrapolate incorrectly, but this could happen.

**Comment by ajs** [comment]
Even outside of testing, though, would it make sense to have a module that just provides the "canned" sequences (e.g. something like `Math::Sequences::OEISPartial`) for every sequence referenced in the other modules? That way, we can use it for testing rather than the download script we have now.

I'd prefer not to import the whole 25MB uncompressed file, but just the referenced sequences makes sense.
